const keywords = [
    'url',
    'method',
    'params',
    'data',
    'headers',
    'auth',
    'proxy',
    'baseURL',
    'transformRequest',
    'transformResponse',
    'paramsSerializer',
    'timeout',
    'withCredentials',
    'adapter',
    'responseType',
    'xsrfCookieName',
    'xsrfHeaderName',
    'onUploadProgress',
    'onDownloadProgress',
    'maxContentLength',
    'validateStatus',
    'maxRedirects',
    'httpAgent',
    'httpsAgent',
    'cancelToken',
    'socketPath',
];

module.exports = (keys) => keys.some(key => keywords.includes(key));
